runtime: nodejs16
instance_class: F2

entrypoint: "node .output/server/index.mjs"

handlers:
  - url: /img
    static_dir: public/img

  - url: /fonts
    static_dir: public/fonts

  - url: /css
    static_dir: public/css

  - url: /_nuxt
    static_dir: public/_nuxt

  - url: /.*
    secure: always
    script: auto

env_variables:
  PORT: 8080
  HOST: "0.0.0.0"
  NITRO_HOST: "0.0.0.0"
  NITRO_PORT: "8080"
  NODE_ENV: "production"
